package com.ncc.kairos.moirai.zeus.api;

import com.ncc.kairos.moirai.zeus.model.StringResponse;
import com.ncc.kairos.moirai.zeus.security.utils.JwtUtils;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.server.ResponseStatusException;

/**
 * Controller Implementation of the Admin Services that is autogenerated by
 * swagger-codegen.
 * 
 * @author Lion Tamer
 */
@Controller
@RequestMapping("${openapi.moiraiZeus.base-path:}")
public class SecurityApiController implements SecurityApi {

    @Autowired
    private JwtUtils jwtUtils;

    @Override
    public ResponseEntity<StringResponse> requestAuthTokenRenewal() {
        String response = jwtUtils.updateJwtTokenExpiration();
        if (StringUtils.isEmpty(response)) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Error parsing response");
        }
        return new ResponseEntity<>(new StringResponse().value(response), HttpStatus.OK);
    }

}
