# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatusTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INITIALIZED = "INITIALIZED"
    PROCESSING = "PROCESSING"
    DONE_PROCESSING = "DONE_PROCESSING"
    PROCESSING_ERROR = "PROCESSING_ERROR"
    PROCESSING_WARNING = "PROCESSING_WARNING"
    WAITING_ON_DATA = "WAITING_ON_DATA"
    def __init__(self):  # noqa: E501
        """StatusTypes - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'StatusTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The statusTypes of this StatusTypes.  # noqa: E501
        :rtype: StatusTypes
        """
        return util.deserialize_model(dikt, cls)
