# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_types import StatusTypes  # noqa: F401,E501
from swagger_server import util


class StatusResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: StatusTypes=None, message: str=None):  # noqa: E501
        """StatusResponse - a model defined in Swagger

        :param status: The status of this StatusResponse.  # noqa: E501
        :type status: StatusTypes
        :param message: The message of this StatusResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'status': StatusTypes,
            'message': str
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message'
        }
        self._status = status
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'StatusResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The statusResponse of this StatusResponse.  # noqa: E501
        :rtype: StatusResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> StatusTypes:
        """Gets the status of this StatusResponse.


        :return: The status of this StatusResponse.
        :rtype: StatusTypes
        """
        return self._status

    @status.setter
    def status(self, status: StatusTypes):
        """Sets the status of this StatusResponse.


        :param status: The status of this StatusResponse.
        :type status: StatusTypes
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this StatusResponse.


        :return: The message of this StatusResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this StatusResponse.


        :param message: The message of this StatusResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
